# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'SunnyMood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SunnyMood
  pod 'SwiftyJSON'
  pod 'Alamofire', '4.9.1'
  pod 'SVProgressHUD'
  pod 'XLPagerTabStrip'
  pod 'PolioPager'
  pod 'SDWebImage', '~> 5.0'
  pod 'Charts'
  pod "BSImagePicker", "~> 3.1"
  pod 'SwiftForms'
  pod 'MJRefresh'

end
